# Generated by Django 3.1.10 on 2021-06-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0060_fix_workflow_unique_constraint'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('church', '0024_auto_20210314_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ourbeliefspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='personalstoriespage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicesindexpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='sundaygatheringspage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='BasicPage',
        ),
        migrations.DeleteModel(
            name='OurBeliefsPage',
        ),
        migrations.DeleteModel(
            name='PersonalStoriesPage',
        ),
        migrations.DeleteModel(
            name='ServicesIndexPage',
        ),
        migrations.DeleteModel(
            name='SundayGatheringsPage',
        ),
    ]
