# Generated by Django 3.1.8 on 2021-04-28 02:08

from django.db import migrations, models
import django.db.models.deletion


def make_crossroads_org(apps, schema_editor):
    Org = apps.get_model("church", "Org")
    org, created = Org.objects.get_or_create(
        name="crossroads"
    )
    org.save()


def migrate_crossroads(apps, schema_editor):
    Org = apps.get_model("church", "Org")
    User = apps.get_model("church", "User")
    ServicePage = apps.get_model("church", "ServicePage")
    org, created = Org.objects.get_or_create(
        name="crossroads"
    )
    for user in User.objects.all():
        user.orgs.add(org)
        user.save()

    for sp in ServicePage.objects.all():
        sp.org = org
        sp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_auto_20210314_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(make_crossroads_org),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='servicepage',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_pages', to='church.org'),
        ),
        migrations.AddField(
            model_name='user',
            name='orgs',
            field=models.ManyToManyField(related_name='users', to='church.Org'),
        ),
        migrations.RunPython(migrate_crossroads),
    ]
