---
version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    environment:
      - DD_TRACE_AGENT_URL=http://datadog:8126
      - DD_ENV=dev
      - DD_SERVICE=crossroads-web
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_DJANGO_CACHE_SERVICE_NAME=crossroads-cache
      - DD_DJANGO_DATABASE_SERVICE_NAME=crossroads-web
      - DD_DJANGO_USE_HANDLER_RESOURCE_FORMAT=true
      - DD_PSYCOPG_SERVICE=crossroads-db
      - DD_PROFILING_ENABLED=true

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=crossroads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile

  datadog:
    environment:
      - DD_APM_ENABLED=true
      - DD_CONTAINER_EXCLUDE="name:app"
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
    build:
      context: ./docker/datadog
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
    ports:
      - "127.0.0.1:8126:8126"
