---
version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    environment:
      - DD_TRACE_AGENT_URL=http://datadog:8126
      - DD_ENV=dev
      - DD_SERVICE=crossroads-web
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_TRACE_ASYNCIO_ENABLED=true
      - DD_DJANGO_CACHE_SERVICE_NAME=crossroads-cache
      - DD_DJANGO_DATABASE_SERVICE_NAME=crossroads-web
      - DD_DJANGO_USE_HANDLER_RESOURCE_FORMAT=true
      - DD_SQLITE_SERVICE=crossroads-db
      - DD_PROFILING_ENABLED=true

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile

  nginx:
    restart: always

  datadog:
    environment:
      - DD_CONTAINER_EXCLUDE="name:datadog"
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
    build:
      context: ./docker/datadog
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
    labels:
      com.datadoghq.ad.logs: >-
        [{
          "source": "app",
          "service": "crossroads-web",
          "log_processing_rules": [{
            "type": "multi_line",
            "name": "log_start_with_date",
            "pattern": "\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}:\d{2},\d{3}"
          }]
        }]
