version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    environment:
      - DJANGO_SECRET=${DJANGO_SECRET}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - POSTMARK_API_KEY=${POSTMARK_API_KEY}
      - DD_API_KEY=${DD_API_KEY}
      - DD_ENV=${DD_ENV}
      - DD_TRACE_AGENT_URL=${DD_TRACE_AGENT_URL}
      - DD_SERVICE=crossroads-web
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_DJANGO_CACHE_SERVICE_NAME=crossroads-cache
      - DD_DJANGO_DATABASE_SERVICE_NAME=crossroads-web
      - DD_DJANGO_USE_HANDLER_RESOURCE_FORMAT=true
      - DD_PSYCOPG_SERVICE=crossroads-db
      - DD_PROFILING_ENABLED=true
    command: ${CIA_SERVER_CMD}
    volumes:
      - .:/app
      - postgres_socket:/var/run/postgresql
      - staticfiles:/app/static
      - ${CIA_MEDIA_DIR}:/app/media
    cap_add:
      - SYS_PTRACE
    ports:
      - 8001:8000

  db:
    image: postgres:13.3
    environment:
      - POSTGRES_DB=crossroads
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ${PG_DATA_DIR}:/var/lib/postgresql/data
      - postgres_socket:/var/run/postgresql

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      - DD_ENV=${DD_ENV}
    command: ${WEB_CMD}
    volumes:
      - .:/app
      - /app/node_modules
      - staticfiles:/static

  nginx:
    platform: linux/x86_64
    build:
      context: ${CIA_NGINX_DOCKER_CTX}
      dockerfile: ./Dockerfile
    ports:
      - ${CIA_PORT}:80
    environment:
      - DD_ENV=${DD_ENV}
    volumes:
      - staticfiles:/static

  datadog:
    image: datadog/agent:7.32.1
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=true
      - DD_CONTAINER_EXCLUDE=name:app
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_PROCESS_AGENT_ENABLED=true
      - DD_LOG_LEVEL=${DD_AGENT_LOG_LEVEL}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - /etc/passwd:/etc/passwd:ro
    ports:
      - "127.0.0.1:8126:8126"

volumes:
  staticfiles:
  postgres_socket:
