version: '3.7'

services:
  dev_server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: ddtrace-run python manage.py runserver 0.0.0.0:${PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"

  dev_datadog:
    env_file:
      - .env
    links:
      - dev_server
    image: datadog/agent:latest
    environment:
      - DD_CONTAINER_EXCLUDE="name:dev_datadog"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - 8126:8126

  prod_server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py loaddata groups &&
             python manage.py loaddata users &&
             ddtrace-run daphne -b 0.0.0.0 -p 8000 crossroads.asgi:application"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app
      - staticfiles:/app/static
    expose:
      - 8000

  prod_nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - staticfiles:/static
    ports:
      - ${PORT}:80
    depends_on:
      - prod_server

  prod_datadog:
    env_file:
      - .env
    environment:
      - DD_CONTAINER_EXCLUDE="name:prod_datadog"
    links:
      - prod_server
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - 8126:8126

volumes:
  staticfiles:
