version: '3.7'

services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: ddtrace-run python manage.py runserver 0.0.0.0:${PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"

  prod_server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py loaddata groups &&
             ddtrace-run daphne -b 0.0.0.0 -p 8000 crossroads.asgi:application"
    restart: always
    env_file:
      - .env.prod
    volumes:
      - .:/code
      - staticfiles:/code/static
    expose:
      - 8000

  prod:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - staticfiles:/static
    ports:
      - ${PORT}:80
    depends_on:
      - prod_server

volumes:
  staticfiles:
