---
version: "3.7"

services:
  app:
    extends:
      file: common.yml
      service: app
    environment:
      - DD_ENV=dev
    command: ddtrace-run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app

  web:
    extends:
      file: common.yml
      service: web
    command: yarn run dev --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
      - /app/node_modules

  nginx:
    extends:
      file: common.yml
      service: nginx
    build:
      context: ./docker/nginx_dev
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8000:80

  datadog:
    extends:
      file: common.yml
      service: datadog
    environment:
      - DD_LOG_LEVEL=INFO
