version: '3.7'

services:
  server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
