version: '3.7'

services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: ddtrace-run python manage.py runserver 0.0.0.0:${PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
      - ./log:/var/log/crossroads/
    ports:
      - "${PORT}:${PORT}"

  prod_server:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --no-input &&
             python manage.py loaddata groups &&
             python manage.py loaddata users &&
             ddtrace-run daphne -b 0.0.0.0 -p 8000 crossroads.asgi:application"
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
      - staticfiles:/code/static
    expose:
      - 8000

  prod:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    volumes:
      - staticfiles:/static
    ports:
      - ${PORT}:80
    depends_on:
      - prod_server

  datadog:
    links:
      - prod_server
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_ENABLED=${DD_APM_ENABLED}
      - DD_LOGS_ENABLED=${DD_LOGS_ENABLED}
      - DD_LOGS_CONFIG_USE_HTTP=true
      - DD_LOGS_CONFIG_USE_COMPRESSION=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
      - ${MY_DD_LOCAL_AGENT_CONF_DIR}:/conf.d:ro

volumes:
  staticfiles:
