version: '3.7'

services:
  dev:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: ddtrace-run python manage.py runserver 0.0.0.0:${PORT}
    restart: always
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"

  prod:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    command: ddtrace-run daphne -b 0.0.0.0 -p ${PORT} crossroads.asgi:application
    restart: always
    env_file:
      - .env.prod
    volumes:
      - .:/code
    ports:
      - "${PORT}:${PORT}"
