version: '3.7'

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/server/Dockerfile
    env_file:
      - .env
    environment:
      - DATADOG_TRACE_AGENT_HOSTNAME=datadog
      - DD_ENV=prod
      - DD_SERVICE=crossroads-web
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_TRACE_ASYNCIO_ENABLED=true
      - DD_DJANGO_CACHE_SERVICE_NAME=crossroads-cache
      - DD_DJANGO_DATABASE_SERVICE_NAME=crossroads-web
      - DD_DJANGO_USE_HANDLER_RESOURCE_FORMAT=true
      - DD_SQLITE_SERVICE=crossroads-db
    secrets:
      - django_secret
      - postmark_api_key
    command: ddtrace-run python manage.py runserver 0.0.0.0:8000
    restart: always

  nginx:
    build:
      context: ./docker/nginx_dev
      dockerfile: ./Dockerfile
    ports:
      - 8000:80
    restart: always
    depends_on:
      - app

  datadog:
    env_file:
      - .env
    environment:
      - DD_CONTAINER_EXCLUDE="name:datadog"
      - DD_APM_ENABLED=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOG_LEVEL=INFO
    secrets:
      - datadog_api_key
    image: ghcr.io/crossroadsinajax/datadog-agent:prod
    build:
      context: ./docker/datadog
      dockerfile: ./Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro

secrets:
  datadog_api_key:
    external: true
  django_secret:
    external: true
  postmark_api_key:
    external: true
