[tool.black]
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.riot
    | media
    | \.venv
  )/
  | migrations
)
'''

[tool.isort]
profile = "black"
skip = [".riot", "node_modules"]
skip_glob = "**/migrations"
