---
version: "3.7"

# Unfortunately we can't extend prod.yml as the volumes
# will be combined rather than overridden.
# This file must be as similar as possible to prod.yml.

services:
  app:
    extends:
      file: common.yml
      service: app
    image: ghcr.io/crossroadsinajax/app:staging
    environment:
      - DD_ENV=staging
      - DJANGO_SETTINGS_MODULE=crossroads.settings.staging
    # TODO: uvicorn gives "Unsupported upgrade request."
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata groups &&
             ddtrace-run daphne -b 0.0.0.0 -p 8000 crossroads.asgi:application"
    secrets:
      - django_secret
      - postmark_api_key
    volumes:
      - staticfiles:/app/static
      - /home/kyle/staging/media:/app/media
      - postgres_socket:/var/run/postgresql

  db:
    extends:
      file: common.yml
      service: db
    volumes:
      - /home/kyle/staging/pg_data:/var/lib/postgresql/data
      - postgres_socket:/var/run/postgresql

  web:
    extends:
      file: common.yml
      service: web
    image: ghcr.io/crossroadsinajax/web:staging
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.prod
    # Outputs app.js to /static/
    # Defined in webpack.prod.js.
    command: yarn run build
    volumes:
      - staticfiles:/static
    deploy:
      restart_policy:
        condition: none

  nginx:
    extends:
      file: common.yml
      service: nginx
    image: ghcr.io/crossroadsinajax/nginx:staging
    build:
      context: ./docker/nginx_prod
      dockerfile: ./Dockerfile
    ports:
      - 8001:80
    volumes:
      - staticfiles:/static

  datadog:
    extends:
      file: common.yml
      service: datadog
    image: ghcr.io/crossroadsinajax/datadog-agent:staging
    environment:
      - DD_API_KEY_FILE=/run/secrets/datadog_api_key
      - DD_ENV=staging
      - DD_LOG_LEVEL=WARNING
    secrets:
      - datadog_api_key

volumes:
  staticfiles:
  postgres_socket:

secrets:
  datadog_api_key:
    external: true
  django_secret:
    external: true
  postmark_api_key:
    external: true
