# Generated by Django 3.1.12 on 2021-06-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_delete_chatlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.CharField(max_length=4096),
        ),
    ]
