# Generated by Django 3.1.7 on 2021-04-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prayer', '0003_auto_20200328_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='prayerrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='prayerrequest',
            name='include_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prayerrequest',
            name='state',
            field=models.CharField(choices=[('ACT', 'Active'), ('RES', 'Resolved')], default='ACT', max_length=3),
        ),
    ]
