name: continuous integration
on: [push]
jobs:
  server:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Pipenv
        run: pip install pipenv

      - name: Install Dependencies
        run: pipenv install

      - name: Format
        run: pipenv run black --check --exclude migrations .

      - name: Lint
        run: pipenv run flake8
  web:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn run tsc

      - name: Format
        run: yarn run prettier --check .

      - name: Lint
        run: yarn run eslint "web/**"
