on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Comment PR with basic message
        uses: actions/checkout@v1
        with:
          message: 'Basic message'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
