name: Publish latest Docker image
on: [push]
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to registry
        run: |
          docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
          docker build -t crossroads-server -f ./docker/server/Dockerfile ./
          docker push crossroads-server

